### PR TITLE
Update rollbar version

### PR DESCRIPTION
**Pull request by caulagi**
Reflect latest version of rollbar in example

### CODE REVIEW

**Comment by scarroll32** [comment]
An ummerged PR from 2017! Wow Rollbar ...

**Comment by ArturMoczulski** [comment]
Thanks @seanfcarroll for bringing this to our attention. I'll review in a bit

**Comment by remarkov** [comment]
I was just passing by and could not resist to note how much impressed I am. Really, no offense at all, I understand we all busy etc. It just gave me a wide smile to see a one line (two chars actually) PR that is three years old and that "...in a bit" is more than a year old now.

That is super cool and I will be giving a link to this when my colleagues will start complaining that it takes too long to review someone's PR.

**Comment by bxsx** [comment]
Hi all, thanks for the contribution and all the patience. The PR is slightly out of date, so I have just updated it to the current state. I also changed the versioning schema, so the example will use the most recent version of our Rollbar SDK now (`0.15 =< pyrollbar < 1.0`).

Once again, thanks @caulagi for the contribution!

PS. @remarkov thanks for the comment! Please keep in mind that this PR didn't affect the example itself. The previously frozen version was working just fine.
[ch79857]

**Review by pawelsz-rb — APPROVED** [review]

**Comment by bxsx** [comment]
The PR has been merged. Thanks everyone for a contribution!

**Pull request merged**
